# -*- coding: utf-8 -*-
"""Practice_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqSZ5JqLnyBh4gm0GBOFlV0sfLiQCG0Y
"""

# Завдання 1
number = int(input("Write an integer: "))

if number % 2 == 0:
  print("even number")
else:
  print("")

# Завдання 2
average_mark = float(input("Write your average mark: "))

if average_mark >= 90:
  print("Well done!")
elif average_mark >= 75:
  print("Not bad!")
else:
  print("You are a fool haha")

# Завдання 3

price = 10

while price in range(10, 100, 5):
  price += 5
  pdv = price * 0.2
  price_2 = price + pdv
  print (f"Ціна без ПДВ: {price} → з ПДВ: {price_2}")

# Завдання 4
number_1 = int(input("Write a first number: "))
number_2 = int(input("Write a second number: "))
number_3 = int(input("Write a third number: "))

if number_1 > number_2 and number_1 > number_3:
  print (number_1)
elif number_2 > number_1 and number_2 > number_3:
  print (number_2)
else:
  print (number_3)

# Завдання 5
value = 1000
month = 0

while value < 5000:
  value += 300
  month += 1
  print (f"money: {value} month: {month}")

# Завдання 6
year = int(input("Write a year bro: "))

if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
  print ("Високосний")
else:
  print ("Звичайний рік")

# Завдання 7
number = 0

while number in range(0,20):
  number += 1
  if number % 4 == 0:
    continue
  print(number)

# Завдання 8
value = 10000
monthly = 1200
num_month = 0

while value >= 0:
  num_month += 1
  remainder = value - monthly
  rate = remainder * 0.02
  value = remainder + rate
  if value > 0:
    print (f"money: {value}, month: {num_month}")

# Завдання бонусне
total_income = 0
while True:
  salary = float(input("Введіть ваш місячний дохід або '0' для виходу: "))
  if salary == 0:
    break
  elif salary < 0:
    print("Дохід не може бути від’ємним")
    continue
  else:
    total_income += salary
    print(f"Ваш дохід збережено: {total_income}")